version: "3"

services:
  indexer:
    image: pinning-service-indexer:latest
    build:
      context: .
      dockerfile: docker/indexer.Dockerfile
    depends_on:
      - jena-fuseki
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file:
      - .env
  jena-fuseki:
    image: stain/jena-fuseki:jena4
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - ./fuseki-data:/fuseki
    environment:
      - ADMIN_PASSWORD=admin
      - FUSEKI_DATASET_1=resources